import { execFileSync } from 'child_process';
import { mkdirSync, writeFileSync, unlinkSync, realpathSync, existsSync, readFileSync } from 'fs';
import { homedir, tmpdir, userInfo } from 'os';
import { join } from 'path';

export const TASK_LABEL = 'dev.tokenphage.sync';
const WIN_TASK_NAME = 'tokenphage-sync';
const SCHEDULE_HOUR = 4;
const SCHEDULE_MINUTE = 0;

/** ~/.tokenphage/logs 디렉터리를 보장하고 sync.log의 절대경로를 반환한다. */
export function ensureLogDir() {
  const dir = join(homedir(), '.tokenphage', 'logs');
  mkdirSync(dir, { recursive: true });
  return join(dir, 'sync.log');
}

/**
 * 스케줄러가 실행할 node 바이너리와 이 CLI 스크립트의 절대경로를 반환한다(심링크는 realpath로 해소).
 * 예) 전역 설치(npm i -g) 상태:
 *   node    = /Users/me/.nvm/versions/node/v22.17.1/bin/node          (process.execPath)
 *   argv[1] = /usr/local/bin/tokenphage                               (← bin 심링크)
 *   script  = /usr/local/lib/node_modules/tokenphage/src/index.js     (realpath로 해소된 실제 파일)
 * 로컬 개발(node src/index.js) 시엔 argv[1]이 이미 실파일이라 script도 그대로 .../src/index.js.
 */
export function resolveTokenphageBinary() {
  const node = process.execPath;
  const script = realpathSync(process.argv[1]);
  return { node, script };
}

// XML 특수문자(& < > " ')를 엔티티로 치환한다 (plist·Task XML 삽입용).
function escapeXml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

// POSIX 셸 single-quote escaping: 경로에 공백·특수문자가 있어도 안전하게 인용한다.
function shSingleQuote(s) {
  return `'${String(s).replace(/'/g, `'\\''`)}'`;
}

// PowerShell single-quote literal escaping: 내부 작은따옴표(')만 ''로 이중화하면 된다.
// cmd 파싱을 거치지 않으므로 공백·% ! ^ & 등 메타문자 걱정이 없다.
function psSingleQuote(s) {
  return `'${String(s).replace(/'/g, `''`)}'`;
}

// ─── macOS (launchd) ────────────────────────────────────────────────────────

// launchd 에이전트 plist 파일 경로 (~/Library/LaunchAgents).
function plistPath() {
  return join(homedir(), 'Library', 'LaunchAgents', `${TASK_LABEL}.plist`);
}

// macOS·Linux 공용 node 탐색 래퍼 셸 스크립트 경로 (~/.tokenphage/run-sync.sh).
function syncScriptPathSh() {
  return join(homedir(), '.tokenphage', 'run-sync.sh');
}

// launchd가 직접 node 절대경로를 들고 있으면 nvm/fnm 등 버전 매니저가
// 경로를 바꾸는 순간 스케줄이 조용히 깨진다. 대신 실행 시점에 node를
// 동적으로 탐색하는 래퍼를 거치게 해, 버전이 바뀌어도 알아서 따라가게 한다.
// 특정 사용자·버전 경로를 plist에 하드코딩하지 않는다.
function buildSyncShellScript(script) {
  return `#!/bin/sh
# tokenphage auto-sync launcher — generated by tokenphage-cli.
# node 바이너리를 실행 시점에 탐색한다 (nvm 등 버전 매니저 변경에도 견고).

# ls/sort/tail/command 등 coreutils가 항상 잡히도록 표준 PATH를 보장한다.
export PATH="/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin:$PATH"

SCRIPT=${shSingleQuote(script)}

resolve_node() {
  # 1) PATH 상의 node (Homebrew / 시스템 / launchd PATH)
  if command -v node >/dev/null 2>&1; then command -v node; return 0; fi
  # 2) nvm: 설치된 버전 중 가장 최신
  nvm_root="$HOME/.nvm/versions/node"
  if [ -d "$nvm_root" ]; then
    newest=$(ls -1 "$nvm_root" 2>/dev/null | sort -V | tail -1)
    if [ -n "$newest" ] && [ -x "$nvm_root/$newest/bin/node" ]; then
      echo "$nvm_root/$newest/bin/node"; return 0
    fi
  fi
  return 1
}

NODE=$(resolve_node)
if [ -z "$NODE" ]; then
  echo "tokenphage: node 바이너리를 찾지 못했습니다 (PATH 및 ~/.nvm 확인)" >&2
  exit 127
fi
exec "$NODE" "$SCRIPT" sync
`;
}

// launchd plist 문자열을 만든다. 매일 정해진 시각에 /bin/sh로 래퍼를 실행하고 stdout/stderr를 로그로 남기게 정의한다.
function buildPlist(wrapperPath, logPath) {
  const home = homedir();
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTD/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${escapeXml(TASK_LABEL)}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>${escapeXml(wrapperPath)}</string>
  </array>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Hour</key><integer>${SCHEDULE_HOUR}</integer>
    <key>Minute</key><integer>${SCHEDULE_MINUTE}</integer>
  </dict>
  <key>RunAtLoad</key>
  <false/>
  <key>StandardOutPath</key>
  <string>${escapeXml(logPath)}</string>
  <key>StandardErrorPath</key>
  <string>${escapeXml(logPath)}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>HOME</key>
    <string>${escapeXml(home)}</string>
    <key>PATH</key>
    <string>/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin</string>
  </dict>
</dict>
</plist>
`;
}

// 기존 launchd 등록을 해제한다 (bootout 실패 시 구버전 unload로 폴백). 성공 여부를 boolean으로 반환.
function launchctlBootout() {
  const uid = userInfo().uid;
  const path = plistPath();
  try {
    execFileSync('launchctl', ['bootout', `gui/${uid}/${TASK_LABEL}`], { stdio: 'ignore' });
    return true;
  } catch {
    try {
      execFileSync('launchctl', ['unload', path], { stdio: 'ignore' });
      return true;
    } catch {
      return false;
    }
  }
}

// plist를 launchd에 등록한다 (bootstrap 실패 시 구버전 load로 폴백, 둘 다 실패하면 안내 메시지와 함께 throw).
function launchctlBootstrap() {
  const uid = userInfo().uid;
  const path = plistPath();
  try {
    execFileSync('launchctl', ['bootstrap', `gui/${uid}`, path], { stdio: 'pipe' });
  } catch (err) {
    try {
      execFileSync('launchctl', ['load', path], { stdio: 'pipe' });
    } catch (err2) {
      const msg = (err2.stderr?.toString() || err.stderr?.toString() || err.message || '').trim();
      throw new Error(`launchctl registration failed: ${msg}\n` +
        'If permission was denied, check System Settings → Privacy & Security → Automation.');
    }
  }
}

// macOS 설치: node 탐색 래퍼 작성 → plist 작성 → launchd 재등록(멱등). 등록 결과 메타(method/logPath 등)를 반환한다.
function installMac() {
  const { script } = resolveTokenphageBinary();
  const logPath = ensureLogDir();
  const path = plistPath();
  const wrapper = syncScriptPathSh();
  mkdirSync(join(homedir(), 'Library', 'LaunchAgents'), { recursive: true });
  mkdirSync(join(homedir(), '.tokenphage'), { recursive: true });

  // node 탐색 래퍼를 먼저 깔고, plist는 이 래퍼를 가리키게 한다.
  writeFileSync(wrapper, buildSyncShellScript(script), { mode: 0o755 });

  // idempotent: 기존 등록 해제 → 덮어쓰기 → 재등록
  launchctlBootout();
  writeFileSync(path, buildPlist(wrapper, logPath), { mode: 0o644 });
  launchctlBootstrap();

  return {
    platform: 'darwin',
    method: 'launchd',
    logPath,
    scheduleSpec: `daily ${String(SCHEDULE_HOUR).padStart(2, '0')}:${String(SCHEDULE_MINUTE).padStart(2, '0')}`,
    artifactPath: path,
  };
}

// macOS 제거: launchd 등록 해제 후 plist·래퍼 파일을 삭제한다(best-effort). removed 여부를 반환.
function uninstallMac() {
  const path = plistPath();
  const wrapper = syncScriptPathSh();
  const fileExisted = existsSync(path);
  // best-effort 해제 — exit code는 신뢰할 수 없다(거짓 양성).
  launchctlBootout();
  if (fileExisted) unlinkSync(path);
  if (existsSync(wrapper)) {
    try { unlinkSync(wrapper); } catch { /* noop */ }
  }
  return { platform: 'darwin', removed: fileExisted };
}

// ─── Windows (Task Scheduler) ────────────────────────────────────────────────

// Windows용 node 탐색 래퍼 PowerShell 스크립트 경로 (~/.tokenphage/run-sync.ps1).
function ps1Path() {
  return join(homedir(), '.tokenphage', 'run-sync.ps1');
}

// 구버전이 만들던 배치 래퍼 — uninstall 시 함께 정리해 잔여물을 남기지 않는다.
function legacyBatPath() {
  return join(homedir(), '.tokenphage', 'run-sync.bat');
}

// schtasks가 작업을 실행할 때의 PATH는 대화형 셸과 달리 제한적이라, 설치 시점
// node 경로를 박아두면 nvm-windows/fnm/volta로 버전을 바꾸는 순간 조용히 깨진다.
// 그래서 macOS 래퍼(buildSyncShellScript)와 동일하게, 실행 시점에 node를 동적
// 탐색하는 PowerShell 래퍼를 거치게 한다. PowerShell은 유니코드에 안전하고(한글
// 홈 경로 mojibake 방지) cmd 메타문자 파싱 문제도 없다.
export function buildSyncPs1(script, logPath) {
  const body = `# tokenphage auto-sync launcher — generated by tokenphage-cli.
# node 바이너리를 실행 시점에 탐색한다 (nvm-windows / fnm / volta 변경에도 견고).

$SCRIPT = ${psSingleQuote(script)}
$LOG    = ${psSingleQuote(logPath)}

# 주어진 루트 하위 디렉터리를 버전 내림차순으로 훑어 첫 node.exe 경로를 반환한다.
function Get-NewestNodeIn($root, $relative) {
  if (-not (Test-Path -LiteralPath $root)) { return $null }
  $dirs = Get-ChildItem -LiteralPath $root -Directory -ErrorAction SilentlyContinue |
    Sort-Object -Property @{ Expression = { try { [version]($_.Name.TrimStart('v')) } catch { [version]'0.0.0' } } } -Descending
  foreach ($d in $dirs) {
    $candidate = Join-Path $d.FullName $relative
    if (Test-Path -LiteralPath $candidate) { return $candidate }
  }
  return $null
}

function Resolve-Node {
  # 1) PATH 상의 node — 가장 권위 있고 대부분의 경우 여기서 끝난다.
  $cmd = Get-Command node -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1
  if ($cmd) { return $cmd.Source }

  # 2) nvm-windows: 심링크 디렉터리 + 버전 설치 루트.
  $nvmRoots = @($env:NVM_SYMLINK, $env:NVM_HOME, (Join-Path $env:APPDATA 'nvm'), 'C:\\nvm4w', 'C:\\nvm')
  foreach ($r in $nvmRoots) {
    if (-not $r) { continue }
    $direct = Join-Path $r 'node.exe'
    if (Test-Path -LiteralPath $direct) { return $direct }
    $found = Get-NewestNodeIn $r 'node.exe'
    if ($found) { return $found }
  }

  # 3) fnm: 정적 PATH 항목이 없어 PATH 폴백으로는 절대 못 잡는 핵심 케이스.
  $fnmRoots = @($env:FNM_DIR, (Join-Path $env:USERPROFILE '.fnm'), (Join-Path $env:APPDATA 'fnm'), (Join-Path $env:LOCALAPPDATA 'fnm'))
  foreach ($r in $fnmRoots) {
    if (-not $r) { continue }
    $found = Get-NewestNodeIn (Join-Path $r 'node-versions') 'installation\\node.exe'
    if ($found) { return $found }
  }

  # 4) volta: shim 디렉터리의 node.exe.
  $voltaBases = @($env:VOLTA_HOME, (Join-Path $env:USERPROFILE '.volta'), (Join-Path $env:ProgramFiles 'Volta'))
  foreach ($b in $voltaBases) {
    if (-not $b) { continue }
    $candidate = Join-Path $b 'bin\\node.exe'
    if (Test-Path -LiteralPath $candidate) { return $candidate }
  }

  # 5) 표준 설치 경로 (공식 설치본 / scoop / chocolatey).
  $pf86 = [Environment]::GetEnvironmentVariable('ProgramFiles(x86)')
  $standard = @()
  if ($env:ProgramFiles)      { $standard += (Join-Path $env:ProgramFiles 'nodejs\\node.exe') }
  if ($pf86)                  { $standard += (Join-Path $pf86 'nodejs\\node.exe') }
  if ($env:USERPROFILE)       { $standard += (Join-Path $env:USERPROFILE 'scoop\\shims\\node.exe') }
  if ($env:ChocolateyInstall) { $standard += (Join-Path $env:ChocolateyInstall 'bin\\node.exe') }
  $standard += 'C:\\ProgramData\\chocolatey\\bin\\node.exe'
  foreach ($s in $standard) {
    if (Test-Path -LiteralPath $s) { return $s }
  }

  return $null
}

$node = Resolve-Node
if (-not $node) {
  Add-Content -LiteralPath $LOG -Value 'tokenphage: node 바이너리를 찾지 못했습니다 (PATH / nvm / fnm / volta 확인)'
  [Console]::Error.WriteLine('tokenphage: node not found')
  exit 127
}
if (-not (Test-Path -LiteralPath $SCRIPT)) {
  Add-Content -LiteralPath $LOG -Value ('tokenphage: sync 스크립트를 찾지 못했습니다: ' + $SCRIPT)
  exit 127
}

# 해석된 node의 디렉터리를 PATH 앞에 붙여 자식 프로세스도 같은 node를 쓰게 한다.
$env:Path = (Split-Path -Parent $node) + ';' + $env:Path

& $node $SCRIPT sync *>> $LOG
exit $LASTEXITCODE
`;
  // PowerShell은 LF/CRLF 모두 읽지만 Windows 관례에 맞춰 CRLF로 통일한다.
  return body.replace(/\r?\n/g, '\r\n');
}

// schtasks /XML에 넘길 작업 정의. Exec는 powershell.exe로 위 래퍼를 호출한다.
// powershell.exe(Windows PowerShell 5.1)는 System32에 상시 존재해 제한 PATH에서도
// 잡히므로 절대경로 대신 이름만 쓴다. StartBoundary는 과거 날짜 하드코딩 대신
// 호출 시점(now) 기준으로 만들어 테스트 가능한 순수 함수로 유지한다.
export function buildTaskXml(ps1FilePath, now = new Date()) {
  const pad = (n) => String(n).padStart(2, '0');
  const start =
    `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}` +
    `T${pad(SCHEDULE_HOUR)}:${pad(SCHEDULE_MINUTE)}:00`;
  const psArgs = `-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "${ps1FilePath}"`;
  return `<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>tokenphage daily sync (managed by tokenphage-cli)</Description>
  </RegistrationInfo>
  <Triggers>
    <CalendarTrigger>
      <StartBoundary>${start}</StartBoundary>
      <Enabled>true</Enabled>
      <ScheduleByDay>
        <DaysInterval>1</DaysInterval>
      </ScheduleByDay>
    </CalendarTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>true</RunOnlyIfNetworkAvailable>
    <ExecutionTimeLimit>PT10M</ExecutionTimeLimit>
    <Enabled>true</Enabled>
    <Hidden>true</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>powershell.exe</Command>
      <Arguments>${escapeXml(psArgs)}</Arguments>
    </Exec>
  </Actions>
</Task>
`;
}

// Windows 설치: PS1 래퍼(UTF-8 BOM) 작성 → Task XML(UTF-16 BOM) 생성 → schtasks /Create /F(멱등).
// 권한 거부 시 관리자 터미널 안내와 함께 throw한다.
function installWindows() {
  const { script } = resolveTokenphageBinary();
  const logPath = ensureLogDir();
  const ps1 = ps1Path();
  mkdirSync(join(homedir(), '.tokenphage'), { recursive: true });

  // node 탐색 래퍼를 먼저 깔고, 작업이 이 래퍼를 가리키게 한다.
  // UTF-8 BOM(﻿)으로 기록해야 PowerShell 5.1이 비ASCII 경로를 올바로 파싱한다.
  writeFileSync(ps1, '﻿' + buildSyncPs1(script, logPath), 'utf8');

  // schtasks /XML은 UTF-16 BOM을 요구한다.
  const xmlPath = join(tmpdir(), `tokenphage-task-${Date.now()}.xml`);
  const xmlBody = buildTaskXml(ps1);
  const buf = Buffer.concat([Buffer.from([0xFF, 0xFE]), Buffer.from(xmlBody, 'utf16le')]);
  writeFileSync(xmlPath, buf);

  try {
    // idempotent: /F 로 기존 작업(레거시 .bat 기반 포함)을 덮어쓴다.
    execFileSync('schtasks', ['/Create', '/TN', WIN_TASK_NAME, '/XML', xmlPath, '/F'], { stdio: 'pipe' });
  } catch (err) {
    const msg = (err.stderr?.toString() || err.message || '').trim();
    if (/access is denied|액세스가 거부|0x80070005|requires elevation/i.test(msg)) {
      throw new Error(
        'schtasks 작업 등록이 거부되었습니다. 관리자 권한 터미널에서 다시 실행하세요.\n' +
        'schtasks registration was denied — run this command from an elevated (Administrator) terminal.');
    }
    throw new Error(`schtasks registration failed: ${msg}`);
  } finally {
    try { unlinkSync(xmlPath); } catch { /* noop */ }
  }

  return {
    platform: 'win32',
    method: 'schtasks',
    logPath,
    scheduleSpec: `daily ${String(SCHEDULE_HOUR).padStart(2, '0')}:${String(SCHEDULE_MINUTE).padStart(2, '0')}`,
    artifactPath: WIN_TASK_NAME,
  };
}

// Windows 제거: schtasks /Delete 후 현재(.ps1)·레거시(.bat) 래퍼를 정리한다. removed 여부를 반환.
function uninstallWindows() {
  let removed = false;
  try {
    execFileSync('schtasks', ['/Delete', '/TN', WIN_TASK_NAME, '/F'], { stdio: 'ignore' });
    removed = true;
  } catch { /* 작업이 없으면 무시 */ }

  // 현재 래퍼(.ps1)와 구버전 래퍼(.bat)를 모두 정리한다.
  for (const p of [ps1Path(), legacyBatPath()]) {
    if (existsSync(p)) {
      try { unlinkSync(p); removed = true; } catch { /* noop */ }
    }
  }
  return { platform: 'win32', removed };
}

// ─── Linux (cron) ─────────────────────────────────────────────────────────────

// crontab 관리 마커: BEGIN..END로 우리 블록만 감싸 멱등 설치/제거 시 식별한다.
export const CRON_BEGIN = `# BEGIN ${TASK_LABEL} (managed by tokenphage-cli — do not edit)`;
export const CRON_END = `# END ${TASK_LABEL}`;

// 매일 04:00 sync를 도는 crontab 블록을 만든다. cron은 PATH가 빈약하므로 명령을
// 직접 부르지 않고 node 탐색 sh 래퍼를 호출하며, 출력은 로그로 리다이렉트한다.
// 인용은 두 계층을 모두 처리한다: shSingleQuote로 셸 인용(공백·특수문자·한글 안전)한
// 뒤, cron 파서가 명령 필드에서 개행으로 해석하는 '%'를 '\%'로 이스케이프한다.
// 경로에 개행이 있으면 단일 crontab 엔트리로 표현할 수 없으므로 설치를 중단한다.
export function buildCronBlock(wrapperPath, logPath) {
  for (const p of [wrapperPath, logPath]) {
    if (/\n/.test(p)) throw new Error(`경로에 개행이 있어 cron 엔트리를 만들 수 없습니다: ${JSON.stringify(p)}`);
  }
  const schedule = `${SCHEDULE_MINUTE} ${SCHEDULE_HOUR} * * *`; // "0 4 * * *"
  const cronArg = (s) => shSingleQuote(s).replace(/%/g, '\\%'); // 셸 인용 후 cron '%' 이스케이프(순서 중요)
  const line = `${schedule} /bin/sh ${cronArg(wrapperPath)} >> ${cronArg(logPath)} 2>&1`;
  return `${CRON_BEGIN}\n${line}\n${CRON_END}`;
}

// 기존 crontab 문자열에서 우리 BEGIN..END 블록만 제거한다(남의 항목은 보존).
// 정규식 대신 라인 단위 매칭으로 사용자 라인을 오검출하지 않는다. 완결된 BEGIN..END
// 페어만 제거하고, END를 못 만난 고아 BEGIN(수동 편집·손상)은 버퍼째 되살려 그 뒤
// 사용자 라인이 통째로 삭제되는 데이터 손실을 막는다(파괴적 해석 대신 보존).
export function removeCronBlock(existing) {
  const lines = String(existing).split('\n');
  const out = [];
  let buffer = null; // 미종료 BEGIN 이후 라인을 임시 보관
  for (const line of lines) {
    if (line === CRON_BEGIN) {
      if (buffer !== null) out.push(...buffer); // 직전 고아 BEGIN 블록은 보존
      buffer = [line];
      continue;
    }
    if (buffer !== null) {
      if (line === CRON_END) { buffer = null; continue; } // 완결 페어 → 제거 확정
      buffer.push(line);
      continue;
    }
    out.push(line);
  }
  if (buffer !== null) out.push(...buffer); // 고아 BEGIN: 아무것도 삭제하지 않고 원문 보존
  return out.join('\n');
}

// 기존 블록 제거 후 새 블록을 append한다. 항상 trailing newline으로 끝낸다
// (vixie-cron은 마지막 줄 개행이 없으면 거부/경고할 수 있음).
export function upsertCronContent(existing, block) {
  const base = removeCronBlock(existing).replace(/\n+$/, ''); // 꼬리 공백 라인 정리
  const body = base.length ? `${base}\n${block}` : block;
  return `${body}\n`;
}

// crontab 바이너리 존재 여부 (최소/distroless 컨테이너엔 없을 수 있음).
function hasCrontab() {
  try {
    execFileSync('sh', ['-c', 'command -v crontab'], { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

// 현재 사용자 crontab 전체를 반환한다. '확정된 빈 crontab'만 ''로 취급하고,
// 그 외 읽기 실패는 fail-closed로 throw한다 — 이 값이 crontab 전체 재기록의 base가
// 되므로, 애매한 실패를 ''로 흡수하면 사용자의 기존 항목을 통째로 덮어쓸 수 있다.
// run/timeout은 조회 경로와 테스트를 위한 주입 지점이다 — 기본값이 실제 동작이라 설치 경로는 그대로다.
function readCrontab(run = execFileSync, timeout = undefined) {
  try {
    // maxBuffer 상향: 대형(정상) crontab이 기본 1MB를 넘겨 ENOBUFS로 오인 실패하는 것을 막는다.
    return run('crontab', ['-l'], { encoding: 'utf8', maxBuffer: 16 * 1024 * 1024, timeout });
  } catch (err) {
    // 빈 crontab: exit≠0 + stderr 'no crontab for <user>' → 이때만 빈 문자열(잃을 항목 없음).
    const stderr = (err.stderr?.toString() || '').toLowerCase();
    if (stderr.includes('no crontab')) return '';
    if (err.code === 'ENOENT') throw new Error('crontab command not found');
    // 그 외(ENOBUFS·권한·일시 I/O 등)는 파괴적 재기록을 막기 위해 중단한다.
    throw new Error(`기존 crontab을 안전하게 읽지 못했습니다 (code=${err.code ?? 'unknown'}). 사용자 항목 소실을 막기 위해 중단합니다.`);
  }
}

// cron 데몬 가동 여부(best-effort). Debian=cron, RHEL=crond, Alpine=busybox crond.
// 탐지 실패가 곧 '안 돎'을 뜻하진 않으므로 경고 판단에만 쓰고 hard-fail하지 않는다.
function detectCronDaemon() {
  try {
    execFileSync('sh', ['-c', 'pgrep -x cron || pgrep -x crond'], { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

// WSL 여부: WSL_DISTRO_NAME env 또는 /proc/version에 microsoft 포함.
function isWSL() {
  if (process.env.WSL_DISTRO_NAME) return true;
  try {
    return /microsoft|wsl/i.test(readFileSync('/proc/version', 'utf8'));
  } catch {
    return false;
  }
}

// Linux 설치: sh 래퍼 작성(멱등) → crontab에 마커 블록 upsert → 데몬/WSL 경고.
function installLinux() {
  if (!hasCrontab()) {
    throw new Error(
      'crontab 명령을 찾을 수 없습니다. cron을 설치한 뒤 다시 시도하세요.\n' +
      '  Debian/Ubuntu: sudo apt install cron\n' +
      '  RHEL 계열:     sudo dnf install cronie');
  }
  const { script } = resolveTokenphageBinary();
  const logPath = ensureLogDir();
  const wrapper = syncScriptPathSh();
  mkdirSync(join(homedir(), '.tokenphage'), { recursive: true });

  // 래퍼를 먼저 깔고, crontab 라인이 이 래퍼를 가리키게 한다.
  writeFileSync(wrapper, buildSyncShellScript(script), { mode: 0o755 });

  // 읽기 → 우리 블록 제거 → 새 블록 append → stdin으로 전체 교체(멱등).
  const next = upsertCronContent(readCrontab(), buildCronBlock(wrapper, logPath));
  execFileSync('crontab', ['-'], { input: next, encoding: 'utf8' });

  // best-effort 경고 — 등록은 성공했으나 실제 발화 조건을 사용자에게 알린다.
  if (!detectCronDaemon()) {
    const startCmd = isWSL()
      ? 'sudo service cron start'
      : 'sudo systemctl enable --now crond 2>/dev/null || sudo systemctl enable --now cron    (WSL: sudo service cron start)';
    console.log('[!] cron 데몬이 실행 중이 아닙니다. 아래로 켜야 04:00 스케줄이 실제로 동작합니다:');
    console.log(`    ${startCmd}`);
  }
  if (isWSL()) {
    console.log('[!] WSL은 인스턴스가 떠 있는 동안에만 cron이 동작합니다(04:00에 PC·WSL이 켜져 있어야 함).');
  }

  return {
    platform: 'linux',
    method: 'cron',
    logPath,
    scheduleSpec: `daily ${String(SCHEDULE_HOUR).padStart(2, '0')}:${String(SCHEDULE_MINUTE).padStart(2, '0')}`,
    artifactPath: `crontab (${TASK_LABEL})`,
  };
}

// Linux 제거: crontab에서 마커 블록 제거 후 래퍼 파일 정리(best-effort). removed 반환.
function uninstallLinux() {
  let removed = false;
  if (hasCrontab()) {
    const current = readCrontab();
    if (current.includes(CRON_BEGIN)) {
      const cleaned = removeCronBlock(current).replace(/\n+$/, '');
      // 남은 내용이 있으면 개행 보장해 기록, 전부 비면 빈 crontab으로 교체.
      execFileSync('crontab', ['-'], { input: cleaned.length ? `${cleaned}\n` : '', encoding: 'utf8' });
      removed = true;
    }
  }
  const wrapper = syncScriptPathSh();
  if (existsSync(wrapper)) {
    try { unlinkSync(wrapper); removed = true; } catch { /* noop */ }
  }
  return { platform: 'linux', removed };
}

// ─── 등록 상태 조회 ───────────────────────────────────────────────────────────

// 조회가 멈추면 CLI 진입이 그대로 블로킹된다 (update-check.js의 FETCH_TIMEOUT_MS와 같은 이유).
const PROBE_TIMEOUT_MS = 3000;

/**
 * launchctl 실패를 등록 상태로 분류한다. 113(서비스 없음)만 확정적 미등록이며,
 * 112(도메인 없음 — SSH 등 비 GUI 세션)·ENOENT(명령 부재)·timeout(SIGTERM)은 판정 불가다.
 * 판정 불가를 미등록으로 오해하면 살아있는 예약에 재등록을 걸어 bootout으로 내려버린다.
 * @returns {'missing'|'unknown'}
 */
export function classifyLaunchctlProbe(err) {
  return err?.status === 113 ? 'missing' : 'unknown';
}

// 설치가 bootstrap gui/<uid>이므로 조회도 같은 도메인을 명시한다.
// launchctl list는 호출자의 암묵 도메인만 조회해 비 GUI 세션에서 오탐한다.
function probeMac(run) {
  const uid = userInfo().uid;
  try {
    run('launchctl', ['print', `gui/${uid}/${TASK_LABEL}`],
      { stdio: 'ignore', timeout: PROBE_TIMEOUT_MS });
    return 'registered';
  } catch (err) {
    return classifyLaunchctlProbe(err);
  }
}

// 종료코드만 판정 근거로 쓴다 — 출력 메시지는 현지화·OEM 코드페이지 탓에 파싱할 수 없다.
function probeWindows(run) {
  try {
    run('schtasks', ['/Query', '/TN', WIN_TASK_NAME],
      { stdio: 'ignore', timeout: PROBE_TIMEOUT_MS, windowsHide: true });
    return 'registered';
  } catch (err) {
    return err.status === 1 ? 'missing' : 'unknown';
  }
}

// readCrontab()을 재사용하고 그 함수의 fail-closed throw만 판정 불가로 흡수한다
// 조회는 CLI 시작을 블로킹하므로 설치 경로와 달리 타임아웃을 반드시 건넨다.
function probeLinux(run) {
  try {
    return readCrontab(run, PROBE_TIMEOUT_MS).includes(CRON_BEGIN) ? 'registered' : 'missing';
  } catch {
    return 'unknown';
  }
}

/**
 * 자동 sync 스케줄이 OS 스케줄러에 실제로 등록돼 있는지 조회한다(읽기 전용).
 * 라벨·작업명은 완전 일치로만 찾는다 — 같은 홈에 다른 dev.tokenphage.* 작업이 있을 수 있다.
 * @param {{ platform?: string, run?: Function }} [deps]
 * @returns {'registered'|'missing'|'unknown'}
 */
export function probeHookRegistration({ platform = process.platform, run = execFileSync } = {}) {
  if (platform === 'darwin') return probeMac(run);
  if (platform === 'win32') return probeWindows(run);
  if (platform === 'linux') return probeLinux(run);
  return 'unknown'; // 미지원 OS는 throw 대신 판정 불가 — 조회 실패로 CLI가 죽지 않게 한다.
}

// ─── Public API ──────────────────────────────────────────────────────────────

/** 현재 OS에 맞는 자동 sync 스케줄을 설치한다 (macOS=launchd / Windows=schtasks / Linux=cron). 그 외 OS는 throw. */
export async function installHook() {
  if (process.platform === 'darwin') return installMac();
  if (process.platform === 'win32') return installWindows();
  if (process.platform === 'linux') return installLinux();
  throw new Error(`Unsupported OS: ${process.platform}. Only macOS, Windows, and Linux are supported.`);
}

/** 현재 OS의 자동 sync 스케줄을 제거한다 (macOS=launchd / Windows=schtasks / Linux=cron). 그 외 OS는 throw. */
export async function uninstallHook() {
  if (process.platform === 'darwin') return uninstallMac();
  if (process.platform === 'win32') return uninstallWindows();
  if (process.platform === 'linux') return uninstallLinux();
  throw new Error(`Unsupported OS: ${process.platform}. Only macOS, Windows, and Linux are supported.`);
}
